# -*- coding: utf-8 -*-
"""IRIS_GBC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KTnCLhET6062JeIBdXJRF0LNmddQ5zxe
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('darkgrid')

from sklearn.datasets import load_iris

iris = load_iris()

iris

dataset = pd.DataFrame(iris.data,columns=iris.feature_names)

dataset

dataset['Target'] = iris.target

dataset

x = dataset.iloc[:,[0,4]].values

y = dataset.iloc[:,4].values

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

from sklearn.ensemble import GradientBoostingClassifier

model = GradientBoostingClassifier()

model.fit(x_train,y_train)

y_pred = model.predict(x_test)

y_pred

y_test

from sklearn.metrics import confusion_matrix,classification_report

print(confusion_matrix(y_test,y_pred))

print(classification_report(y_test,y_pred))



